export const CREATE_POEM_FAILURE = "CREATE_POEM_FAILURE";
export const CREATE_POEM_REQUEST = "CREATE_POEM_REQUEST";
export const CREATE_POEM_SUCCESS = "CREATE_POEM_SUCCESS";

export const FETCH_POEM_FAILURE = "FETCH_POEM_FAILURE";
export const FETCH_POEM_REQUEST = "FETCH_POEM_REQUEST";
export const FETCH_POEM_SUCCESS = "FETCH_POEM_SUCCESS";

export const FETCH_POEMS_FAILURE = "FETCH_POEMS_FAILURE";
export const FETCH_POEMS_REQUEST = "FETCH_POEMS_REQUEST";
export const FETCH_POEMS_SUCCESS = "FETCH_POEMS_SUCCESS";
