export const CREATE_POEM_FAILURE = "CREATE_POEM_FAILURE";
export const CREATE_POEM_REQUEST = "CREATE_POEM_REQUEST";
export const CREATE_POEM_SUCCESS = "CREATE_POEM_SUCCESS";

export const FETCH_IDS_FAILURE = "FETCH_IDS_FAILURE";
export const FETCH_IDS_REQUEST = "FETCH_IDS_REQUEST";
export const FETCH_IDS_SUCCESS = "FETCH_IDS_SUCCESS";

export const FETCH_POEM_FAILURE = "FETCH_POEM_FAILURE";
export const FETCH_POEM_REQUEST = "FETCH_POEM_REQUEST";
export const FETCH_POEM_SUCCESS = "FETCH_POEM_SUCCESS";
